<?php

class Iphone extends MobilePhone
{
private int $memory;
private int $appNumber ;

    /**
     * @param int $memory
     * @param int $appNumber
     */
    public function __construct(float $_height, float $_width, int $_autonomy, int $_battery, int $_chargingTime,int $memory, int $appNumber)
    {
        parent::__construct ($_height, $_width,  $_autonomy, $_battery, $_chargingTime);
        $this->memory = $memory;
        $this->appNumber = $appNumber;
    }
public function __destruct()
{
echo "Destruction de l'objet imminente";
}
    public function getMemory(): int
    {
        return $this->memory;
    }

    public function setMemory(int $memory): void
    {
        $this->memory = $memory;
    }

    public function getAppNumber(): int
    {
        return $this->appNumber;
    }

    public function setAppNumber(int $appNumber): void
    {
        $this->appNumber = $appNumber;
    }

    protected function Start()
    {
        if ($this->battery>0&& $this->isOn==false)
        {
            $this->isOn=true;
            $this->battery--;
            echo "l'iphone s'allume et une belle pomme s'affiche!";
        }
        elseif  ($this->battery<=0)
        {
            echo "Le téléphone n'a plus de batterie!";
        }

        elseif ($this->isOn==true)
        {
            echo "le téléphone est déjà allumé";
        }
    }
    public function ShowBatteryPercentage()
    {
        parent::ShowBatteryPercentage(); // TODO: Change the autogenerated stub

        echo "Je suis un Iphone";
    }
}

