use Blindcode;
    SELECT PRENOM,NOM,SEXE,NAISSANCE FROM ELEVE
    ORDER BY NOM;
SELECT PRENOM,NOM,SEXE,NAISSANCE FROM ELEVE
ORDER BY PRENOM;
SELECT PRENOM,NOM,SEXE,NAISSANCE FROM ELEVE
ORDER BY NOM DESC;
SELECT PRENOM,NOM,SEXE,NAISSANCE FROM ELEVE
ORDER BY NAISSANCE ;
SELECT PRENOM,NOM,SEXE,NAISSANCE FROM ELEVE
ORDER BY NAISSANCE DESC ;